# **Contexto**
Un equipo de investigadores está recopilando información sobre observaciones de animales realizadas en diferentes países de Europa Central y Oriental.
Los datos fueron recolectados por diferentes personas y presentan problemas de calidad: valores faltantes, registros duplicados, formatos inconsistentes, errores en los datos y diferentes formas de representar algunas variables.
Antes de realizar cualquier análisis, es necesario diagnosticar y limpiar la información.
Tu trabajo como analista de datos será preparar esta base para que pueda ser utilizada posteriormente en un análisis de biodiversidad.

## **DIAGNOSTICO INICIAL**

In [2]:
import pandas as pd
import numpy as np

path = "/home/aivan/code/Entregables-BIT-IH/Entregas/Animal-data/Datos/animal_data_dirty1.csv"

df_raw = pd.read_csv(path, sep=";")
df = df_raw.copy()

print(f" ¿Cuántas filas y columnas tiene el DataFrame?\n" , df.shape)

 ¿Cuántas filas y columnas tiene el DataFrame?
 (1011, 11)

Se pueden indentificar 1011 registros y 11 columnas en el DF

In [3]:
df.head()

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.01.2024,James Johnson
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03.02.2024,James Johnson
2,European bison,Poland,930.0,335.0,male,NaN,52.828845,23.820144,Szefu,01.03.2024,Anne Anthony
3,European bison,Poland,909.0,311.0,not determined,NaN,52.830509,23.826849,NaN,01.03.2024,Anne Anthony
4,European bison™,Poland,581.0,277.0,female,NaN,52.834109,23.807093,NaN,01.03.2024,Anne Anthony

Visualizando las primeras filas del DF podemos ver que las dos primeras filas no contienen datos excepto por "observation date" y "data compiled by"

In [4]:
df.tail()

,Animal type,Country,Weight kg,Body Length cm,Gender,Animal code,Latitude,Longitude,Animal name,Observation date,Data compiled by
1006,red squirrel,Poland,0.346,20.0,female,NaN,52.212001,21.033187,Lola,7 May 2024,Anne Anthony
1007,hedgehog,Germany,1.000,23.0,female,NaN,49.561356,11.105334,NaN,7 May 2024,Bob Bobson
1008,hedgehog,Germany,0.500,17.0,female,NaN,49.561569,11.087046,NaN,7 May 2024,Bob Bobson
1009,red squirrel,Poland,0.346,20.0,female,NaN,52.212001,21.033187,Lola,7 May 2024,Anne Anthony
1010,hedgehog,Hungary,0.900,16.0,female,NaN,47.509860,18.939943,NaN,8 May 2024,Anne Anthony

profundizando el analisis con la visualizacion parcial del final del DF podemos inferir que la columna [Animal code] esta vacia y que la columna [Animal Name] carece de informacion.

## **¿Cuáles son las columnas y qué tipo de dato tiene cada una?**

In [5]:
## ¿Cuáles son las columnas y qué tipo de dato tiene cada una?
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1011 entries, 0 to 1010
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Animal type       991 non-null    str
 1   Country           999 non-null    str
 2   Weight kg         984 non-null    float64
 3   Body Length cm    984 non-null    float64
 4   Gender            992 non-null    str
 5   Animal code       0 non-null      float64
 6   Latitude          913 non-null    float64
 7   Longitude         913 non-null    float64
 8   Animal name       52 non-null     str
 9   Observation date  1011 non-null   str
 10  Data compiled by  1011 non-null   str
dtypes: float64(5), str(6)
memory usage: 87.0 KB

Podemos identificar que la columna Animal code no contiene informacion por lo que no aporta valor al analisis en ninguna dimension

## **¿Cuántos valores faltantes existen por columna?**

In [6]:
display(
    df.isna()
        .sum()
        .sort_values(ascending=False)
)

Animal code         1011
Animal name          959
Latitude              98
Longitude             98
Weight kg             27
Body Length cm        27
Animal type           20
Gender                19
Country               12
Observation date       0
Data compiled by       0
dtype: int64

Mediante el metodo .isna() validamos los valores faltantes por columna, confirmando que Animal code no aporta valor estadistico a este analisis.

## **¿Cuántos registros duplicados existen?**

In [7]:
duplicados = int(
    df.duplicated()
    .sum()
)

print("Existen en total", {duplicados} , "duplicados")

Existen en total {167} duplicados

Pasamos a identificar a los registro duplicados e indentifacamos 167

#### **Utiliza unique() o value_counts() para identificar categorías inconsistentes o valores sospechosos.**

##### Ahora mediante el metodo .unique() identificamos valores unicos 
##### **Animal Name:**

In [8]:
df["Animal name"].unique()

<StringArray>
[         nan,      'Szefu',      'Basia',      'Lolek',       'Lola',
 'Bob Bobson',     'Klucha',      'Zuzia',       'Bibi',      'Sissi',
   'Puchatek']
Length: 11, dtype: str

In [9]:
df["Animal name"].value_counts()

Animal name
Bob Bobson    18
Basia         10
Lola           9
Lolek          4
Zuzia          4
Sissi          2
Puchatek       2
Szefu          1
Klucha         1
Bibi           1
Name: count, dtype: int64

##### **Latitude:**

In [10]:
df["Latitude"].unique()

array([       nan,  52.828845,  52.830509,  52.834109,  52.834759,
        52.83496 ,  48.505494,  48.506529,  52.241273,  52.24206 ,
        52.240035,  52.240284,  52.24056 ,  52.241177,  52.240833,
        52.241358,  52.241905,  47.511401,  52.24192 ,  49.054684,
        49.053629,  49.053489,  49.054166,  49.052731,  49.055974,
        49.053342,  49.056471,  50.636564,  49.055537,  50.636869,
        50.644733,  50.635766,  48.185353,  50.642843,  48.504128,
        52.809851,  50.641008,  50.643406,  50.638945,  50.639869,
        50.643039,  50.637879,  50.643254,  50.643854,  50.635584,
        50.642723,  50.639389,  48.409308,  47.510799,  50.637375,
        48.406304,  48.18769 ,  52.834741,  48.503795,  48.503062,
        48.503498,  48.509298,  52.214679,  48.504169,  48.505251,
        48.502584,  48.505512,  48.50578 ,  48.502091,  52.241203,
        52.240018,  52.239931,  52.241856,  52.240453,  52.241662,
        52.241638,  48.502803,  52.240497,  50.635501,  50.638142,
        49.937872,  48.185194,  48.503043,  52.240867,  52.240522,
        47.507002,  47.507557,  50.107284,  48.413226,  48.409023,
        48.406733,  48.40459 ,  48.408318,  48.412458,  48.406551,
        48.405516,  52.834423,  52.214521,  52.214934,  48.511532,
        52.241235,  50.106942,  50.107223,  50.106379,  50.106579,
        48.188008,  48.185298,  52.831879,  48.506206,  48.50509 ,
        48.504425,  48.505617,  48.503254,  48.502359,  48.511048,
        48.501574,  52.808579,  -2.023546,  48.505406,  48.503917,
        52.240616,  50.636161,  50.642592,  50.636423,  50.106607,
        50.106925,  49.938634,  48.506913,  52.214365,  47.507023,
        50.106811,  50.107278,  52.828561,  52.833261,  52.21441 ,
        52.214452,  48.508239,  48.507503,  52.814984,  52.812647,
        52.241375,  47.50938 ,  50.106583,  50.10696 ,  50.106311,
        49.937416,  48.51108 ,  48.50529 ,  48.502486,  48.509272,
        48.50118 ,  49.938707,  49.937531,  49.93789 ,  49.93734 ,
        52.834112,  48.505634,  52.214968,  48.501938,  48.506217,
        48.505737,  48.506095,  48.506429,  48.50586 ,  48.502521,
        48.503752,  52.241093,  49.937391,  52.829512,  52.240707,
        47.508454,  49.938169,  49.938527,  49.937724,  48.506262,
        52.214734,  48.504717,  52.24151 ,  47.505768,  48.161549,
        49.939297,  48.185953,  52.821135,  48.509199,  52.213985,
        52.213877,  52.241309,  47.508679,  47.781689,  47.781139,
        47.781828,  47.78106 ,  47.780872,  47.781117,  47.780779,
        47.781257,  49.93849 ,  52.214498,  52.803129,  49.938132,
        48.184374,  49.93886 ,  49.938357,  52.820739,  48.501763,
        52.814211,  52.802757,  52.240529,  47.509866,  48.185585,
        52.82288 ,  48.504773,  52.214745,  47.510304,  49.056857,
        48.41237 ,  48.406983,  48.411486,  48.410536,  52.8255  ,
        52.240737,  49.938547,  49.937429,  49.939062,  48.502512,
        52.214758,  47.781212,  47.781764,  47.781883,  47.781093,
        52.585958,  52.586199,  52.586589,  52.587327,  52.585937,
        49.937696,  48.405926,  48.184757,  48.186767,  52.214754,
        52.215034,  52.241637,  47.505786,  49.937455,  48.407449,
        52.820447,  52.214156,  52.831229,  52.832726,  50.041479,
        50.041154,  47.506414,  47.781236,  47.781248,  52.585628,
        52.58329 ,  47.781106,  52.581896,  52.581885,  52.587248,
        52.58237 ,  50.638137,  50.640733,  50.636642,  49.939474,
        49.938958,  48.185898,  48.186672,  48.18685 ,  52.82547 ,
        52.584352,  52.587863,  52.587734,  52.582754,  52.585517,
        52.588834,  50.644813,  50.635565,  50.639856,  49.939165,
        49.937562,  49.939201,  48.410693,  52.824079,  52.826081,
        52.215039,  52.215085,  50.04186 ,  47.51026 ,  49.937454,
        49.937788,  50.04113 ,  50.041522,  47.781882,  47.781019,
        47.319782,  47.32002 ,  47.318793,  47.316963,  52.582072,
        52.58572 ,  52.587827,  52.583004,  52.587058,  52.587539,
        52.587183,  52.586487,  52.588779,  52.587089,  47.781847,
        47.781296,  47.781538,  47.781345,  52.582658,  49.938688,
        49.939212,  48.186611,  52.214494,  52.214419,  49.937893,
        49.939262,  48.239854,  48.22668 ,  48.23862 ,  52.82429 ,
        52.825554,  50.041235,  47.508618,  49.93915 ,  49.938346,
        52.214766,  50.041489,  52.587532,  48.161584,  48.160459,
        48.160834,  49.938845,  49.938959,  49.939097,  48.226708,
        49.938523,  52.807537,  50.041504,  50.041119,  49.937805,
        49.93933 ,  47.507157,  47.780752,  47.781078,  47.781088,
        48.409138,  48.409448,  50.041382,  48.160773,  48.160813,
        48.161605,  48.162593,  48.16142 ,  48.162549,  48.161646,
        48.405213,  49.939   ,  48.224897,  48.228961,  52.805402,
        50.041366,  47.509538,  48.407464,  48.40979 ,  52.807403,
        52.803733,  50.041804,  47.511558,  48.409754,  50.884012,
        49.939191,  48.23123 ,  52.824599,  50.041131,  50.041552,
        50.041945,  50.041925,  47.511582,  47.319091,  48.161892,
        48.161218,  48.161452,  48.160915,  48.162169,  49.54629 ,
        49.559558,  47.781613,  47.781637,  47.781838,  47.780925,
        47.781449,  47.7818  ,  47.781073,  48.162251,  48.160432,
        48.162563,  48.161906,  49.562324,  49.561973,  47.781755,
        49.557527,  48.411163,  48.410771,  48.410201,  48.408111,
        48.410932,  48.227614,  47.50826 ,  49.551211,  49.562583,
        49.547597,  48.40912 ,  49.938787,  52.809543,  47.508516,
        47.508941,  50.041819,  50.0418  ,  47.508905,  52.811204,
        47.507073,  47.31758 ,  47.31947 ,  47.319812,  47.316383,
        47.781131,  47.781632,  47.780904,  47.781089,  47.781333,
        47.780927,  47.856032,  49.545913,  49.550428,  49.558869,
        48.412408,  50.883894,  48.229837,  52.808704,  47.510231,
        47.509073,  50.041252,  47.855007,  48.409645,  50.883881,
        49.93931 ,  49.938616,  49.937839,  49.939308,  52.803316,
        47.506638,  52.823016,  47.508665,  47.510978,  47.857586,
        47.856971,  47.856769,  47.855379,  47.856015,  48.413154,
        50.041147,  47.853881,  47.854855,  47.855216,  47.857495,
        47.853875,  47.854756,  47.854099,  50.645077,  48.41259 ,
        49.057599,  49.053175,  49.054663,  49.055275,  49.052914,
        49.055453,  49.056583,  49.054586,  49.056946,  50.041497,
        47.509375,  49.937425,  49.939072,  52.809086,  52.821625,
        48.409469,  50.107147,  52.810989,  47.507081,  50.041347,
        47.506071,  47.509655,  47.856092,  47.854876,  47.857535,
        48.162437,  48.161106,  48.161385,  48.162137,  48.162162,
        48.40855 ,  50.106721,  52.80356 ,  48.160992,  48.408713,
        50.106483,  47.511267,  50.041573,  50.041554,  52.211967,
        48.412843,  48.407138,  47.509261,  52.824608,  47.506306,
        47.510068,  47.51106 ,  48.160831,  52.808503,  47.511427,
        52.211888,  48.161422,  48.16079 ,  48.161009,  48.160807,
        48.161794,  48.161069,  48.16087 ,  48.16056 ,  48.409909,
        50.106373,  47.50643 ,  47.506663,  47.508169,  48.161902,
        49.554765,  49.558466,  48.407605,  52.212379,  49.556052,
        49.55152 ,  49.553737,  49.560442,  49.560723,  49.55879 ,
        49.545857,  49.554685,  48.186112,  48.411117,  50.106413,
        50.107135,  52.804031,  49.561057,  49.557055,  49.554133,
        49.561174,  49.563085,  49.551318,  49.556237,  49.545768,
        50.107313,  52.809106,  52.212042,  47.319579,  47.317974,
        47.316562,  47.318191,  50.643056,  48.187522,  48.185406,
       -78.582972,  48.408549,  50.882924,  52.212168,  52.211797,
        52.21247 ,  52.211872,  52.805299,  48.186208,  52.212605,
        52.212001, -78.582973,  48.184231,  52.812486,  52.212045,
        47.781188,  47.780999,  48.185648,  52.851841,  52.212203,
        48.185433,  52.212763,  48.186913,  48.185649,  52.848214,
        52.853843,  52.21212 ,  49.55324 ,  49.551562,  49.547376,
        49.560178,  49.558968,  48.18637 ,  47.506035,  52.21239 ,
        48.183848,  48.410551,  52.212433,  52.212746,  48.23276 ,
        47.509595,  47.511301,  52.212148,  49.56023 ,  49.54841 ,
        48.239628,  47.507376,  52.212429,  48.231939,  52.21284 ,
        52.212163,  48.225014,  47.506311,  52.212553,  48.225116,
        52.212411,  47.507019,  48.237386,  47.510077,  47.507758,
        52.212542,  52.212628,  52.21294 ,  48.235981,  48.23493 ,
        48.412724,  52.211896,  52.211924,  47.510584,  48.236605,
        48.411436,  52.212295,  52.212915,  52.212601,  48.231497,
        48.238634,  52.212245,  52.212583,  52.212065,  48.231214,
        50.881878,  52.212305,  48.231411,  52.212906,  52.82211 ,
        48.237588,  48.232775,  52.821631,  52.821524,  48.22689 ,
        48.412941,  48.237124,  52.82295 ,  52.820813,  52.825793,
        52.820308,  48.228141,  48.408025,  52.823959,  52.825746,
        52.823595,  52.825363,  52.821958,  52.823084,  48.238913,
        48.237762,  48.238517,  48.232384,  50.881376,  50.883325,
        48.408917,  50.881428,  50.882642,  50.883849,  50.884288,
        48.411736,  48.41179 ,  50.881003,  48.406339,  48.411729,
        49.054132,  49.055962,  49.055646,  49.05291 ,  49.055547,
        49.054647,  48.226063,  48.238067,  48.23954 ,  49.057284,
        49.054751,  49.05593 ,  48.413928,  49.057758,  48.185695,
        48.18604 ,  47.509755,  47.507053,  52.211985,  48.184621,
        48.406669,  52.846379,  52.852069,  52.212911,  48.162609,
        48.408475,  47.509103,  48.183927,  52.21231 ,  47.510697,
        47.505903,  52.847483,  49.56122 ,  49.559523,  49.547725,
        48.185893,  48.187845,  48.184278,  52.21276 ,  52.212497,
        52.212144,  48.187468,  47.510055,  49.561356,  49.561569,
        47.50986 ])

In [11]:
df["Latitude"].value_counts()

Latitude
 52.241638    4
-2.023546     4
 50.041366    4
 52.211797    4
 52.212001    4
             ..
 48.187468    1
 47.510055    1
 49.561356    1
 49.561569    1
 47.509860    1
Name: count, Length: 735, dtype: int64

#### **Longitude**

In [12]:
df["Longitude"].value_counts()

Longitude
34.896734    4
21.055745    2
21.057802    2
21.056188    2
21.051948    2
            ..
17.088827    1
18.944356    1
11.105334    1
11.087046    1
18.939943    1
Name: count, Length: 743, dtype: int64

In [13]:
df["Longitude"].unique()

array([      nan, 23.820144, 23.826849, 23.807093, 23.817201, 23.82075 ,
       20.551966, 20.554548, 21.055745, 21.057802, 21.056188, 21.051948,
       21.055899, 21.052873, 21.052093, 21.056352, 21.050727, 18.949119,
       21.056347, 22.417189, 22.421831, 22.415229, 22.422852, 22.422675,
       22.415985, 22.423867, 22.422475, 14.834553, 22.419428, 14.844555,
       14.835753, 14.844247, 17.08322 , 14.84124 , 20.568479, 23.858071,
       14.836529, 14.836495, 14.845452, 14.849702, 14.840662, 14.838429,
       14.84373 , 14.837155, 14.837072, 14.837229, 14.8444  , 18.832606,
       18.945583, 14.839785, 18.842851, 17.086471, 23.826716, 20.555932,
       20.551698, 20.539662, 20.551977, 21.033021, 20.559452, 20.551473,
       20.532518, 20.538038, 20.546466, 20.547521, 20.536362, 21.050999,
       21.05239 , 21.056703, 21.053078, 21.055847, 21.05643 , 21.055998,
       20.548668, 21.055991, 14.838158, 14.849689, 14.179825, 17.083142,
       20.561567, 21.054339, 21.057552, 18.950091, 18.942066, 14.346127,
       18.848128, 18.84399 , 18.838754, 18.846849, 18.844383, 18.832425,
       18.837137, 18.850994, 23.827103, 21.031889, 21.032106, 20.539112,
       21.057329, 21.057356, 14.348502, 14.34732 , 14.347645, 14.346283,
       17.085312, 17.084072, 23.826297, 20.565308, 20.539448, 20.548744,
       20.541054, 20.555951, 20.563385, 20.567209, 20.532455, 23.843768,
       34.896734, 20.535848, 20.536503, 21.054902, 14.846951, 14.85014 ,
       14.847287, 14.347909, 14.346629, 14.347676, 14.181813, 20.540427,
       21.031462, 18.940532, 14.348513, 14.348461, 23.816861, 23.815203,
       21.032484, 21.034505, 20.567914, 20.551726, 23.840681, 23.863299,
       21.050845, 18.949607, 14.346471, 14.346126, 14.346906, 14.181449,
       20.567192, 20.566169, 20.562565, 20.551952, 20.557432, 14.182507,
       14.180359, 14.180882, 14.18071 , 23.825722, 20.543417, 21.030987,
       20.567814, 20.545055, 20.546731, 20.543032, 20.543875, 20.547649,
       20.558578, 20.558664, 21.055413, 14.179566, 23.811681, 21.057051,
       18.949343, 14.178703, 14.179315, 14.182072, 20.547343, 21.031915,
       20.558726, 21.052575, 18.943674, 11.493041, 14.181453, 17.08393 ,
       23.809947, 20.552447, 21.030841, 21.030861, 21.057247, 18.946127,
       14.386777, 14.382004, 14.385001, 14.386807, 14.38446 , 14.38608 ,
       14.384918, 14.383099, 14.1802  , 21.034201, 23.844358, 14.181225,
       17.086   , 14.182738, 14.177929, 23.815145, 20.547976, 23.834358,
       23.835199, 21.053603, 18.942538, 17.091365, 23.810852, 20.536543,
       21.033701, 18.942925, 22.416369, 18.875325, 18.863197, 18.86773 ,
       18.870325, 23.808386, 21.053063, 14.180402, 14.18264 , 14.179739,
       14.177939, 20.563331, 21.030697, 14.384017, 14.38328 , 14.382628,
       14.38209 , 13.147098, 13.152793, 13.146651, 13.149206, 13.146151,
       14.182707, 18.839219, 17.082936, 17.089935, 21.034364, 21.03303 ,
       21.05154 , 18.943124, 14.180775, 18.850762, 23.813259, 21.0325  ,
       23.814123, 23.825032, 19.951211, 19.949919, 18.941655, 14.382219,
       14.382649, 13.149093, 13.149155, 14.382184, 13.151801, 13.152811,
       13.151499, 13.146855, 14.838129, 14.84516 , 14.847946, 14.180897,
       14.181258, 17.090683, 17.091508, 17.091228, 23.81307 , 13.148089,
       13.147785, 13.151378, 13.145364, 13.150878, 13.15192 , 14.839817,
       14.83932 , 14.847626, 14.17875 , 14.182528, 14.181101, 14.178923,
       18.832845, 23.81279 , 23.815823, 21.032591, 21.034198, 19.950192,
       18.947838, 14.182121, 14.180368, 19.949698, 19.950563, 14.384802,
       14.385089, 11.190836, 11.18557 , 11.185855, 11.188761, 13.149185,
       13.148613, 13.148164, 13.150686, 13.149675, 13.146575, 13.146661,
       13.150015, 13.147948, 13.151807, 14.386835, 14.383799, 14.384561,
       14.382936, 13.148057, 14.179603, 14.180839, 17.090271, 21.033154,
       21.033441, 14.18083 , 14.179613, 17.086693, 17.081529, 17.074393,
       23.813465, 23.812594, 19.951284, 18.944915, 14.179388, 14.18024 ,
       21.030532, 19.950768, 13.152361, 11.494938, 11.493142, 11.489874,
       14.182246, 14.180078, 14.179435, 17.087853, 14.18244 , 23.700909,
       19.950218, 19.94973 , 14.179716, 14.177877, 18.940379, 14.383452,
       14.384559, 14.385534, 18.863577, 18.845591, 19.949403, 11.49368 ,
       11.492539, 11.49115 , 11.491872, 11.495056, 11.492991, 11.493511,
       18.84085 , 14.182239, 17.085979, 17.076478, 23.691244, 19.949444,
       18.945968, 18.87406 , 18.870341, 23.683044, 23.686928, 19.951361,
       18.942454, 18.870477, 14.370554, 14.180256, 17.090253, 23.816842,
       19.949543, 19.949984, 19.94932 , 19.950894, 18.942341, 11.188058,
       11.493888, 11.494677, 11.495239, 11.489927, 11.495473, 11.085729,
       11.08115 , 14.385153, 14.385383, 14.382938, 14.383695, 14.383421,
       14.383699, 14.383506, 11.494811, 11.494472, 11.495277, 11.490434,
       11.092212, 11.086554, 14.385083, 11.089447, 18.864362, 18.865888,
       18.862513, 18.865646, 18.861704, 17.072903, 18.948349, 11.077661,
       11.082312, 11.079679, 18.869274, 14.178284, 23.708564, 18.949429,
       18.948915, 19.951542, 19.950244, 18.94657 , 23.697814, 18.947873,
       11.187606, 11.18573 , 11.18479 , 11.188381, 14.382207, 14.382365,
       14.385669, 14.385211, 14.382547, 14.382188, 15.076768, 11.081051,
       11.077659, 11.076638, 18.869074, 14.372364, 17.089218, 23.705504,
       18.940042, 18.946838, 19.950033, 15.076539, 18.872415, 14.373018,
       14.181266, 14.181291, 14.179075, 14.180747, 23.686301, 18.940091,
       23.812286, 18.940456, 18.942963, 15.081328, 15.078984, 15.076411,
       15.077237, 15.08325 , 18.875356, 19.95046 , 15.078367, 15.082168,
       15.078877, 15.07895 , 15.078745, 15.082892, 15.076812, 14.840304,
       18.87302 , 22.422203, 22.414666, 22.412082, 22.41421 , 22.42299 ,
       22.423536, 22.415432, 22.41368 , 22.424916, 19.950657, 18.939808,
       14.182723, 14.180063, 23.696425, 23.818063, 18.861715, 14.347009,
       23.689137, 18.939062, 19.950773, 18.949311, 18.943576, 15.083547,
       15.08295 , 15.078083, 11.494298, 11.48991 , 11.492571, 11.494415,
       11.493917, 18.864935, 14.346231, 23.690378, 11.495374, 18.863829,
       14.348192, 18.940191, 19.949936, 19.94985 , 19.95113 , 21.032924,
       18.872614, 18.867247, 18.949967, 23.817396, 18.946099, 18.947176,
       18.939832, 11.492403, 23.69937 , 18.948714, 21.03235 , 11.491813,
       11.489549, 11.491557, 11.494219, 11.494325, 11.49303 , 11.49027 ,
       11.490806, 18.867006, 14.347574, 18.947912, 18.94032 , 18.947418,
       11.49458 , 11.0922  , 11.096048, 18.876341, 21.032913, 11.081501,
       11.079537, 11.087705, 11.098395, 11.084667, 11.081218, 11.076254,
       11.08345 , 17.090491, 18.862265, 14.348204, 14.348206, 23.683032,
       11.084334, 11.101996, 11.089674, 11.102216, 11.101392, 11.085475,
       11.088639, 11.086386, 14.348552, 23.680095, 21.033492, 11.186061,
       11.187472, 11.19116 , 11.189484, 14.843037, 17.087251, 17.084535,
       14.367993, 18.87396 , 14.368207, 21.032304, 21.03375 , 21.033642,
       21.032296, 23.701093, 17.089749, 21.033877, 21.033903, 14.366824,
       17.091694, 23.686231, 21.032857, 21.031986, 14.385356, 14.38212 ,
       17.083763, 23.89158 , 21.032279, 17.086216, 21.032786, 17.088174,
       17.088834, 23.891978, 23.919668, 21.034268, 11.074008, 11.081737,
       11.079529, 11.093259, 11.106642, 17.090384, 18.944528, 21.034548,
       17.082806, 18.864866, 21.032496, 21.033832, 17.069049, 18.939751,
       18.93974 , 21.033421, 11.102233, 11.078249, 17.087298, 18.9396  ,
       21.032435, 17.087688, 21.034377, 21.032633, 17.081449, 18.947371,
       21.032768, 17.086408, 21.033173, 18.944015, 17.078352, 18.945646,
       18.949223, 21.033829, 21.034494, 21.034208, 17.081698, 17.084813,
       18.868878, 21.033806, 21.033243, 18.94173 , 17.071495, 18.86478 ,
       21.034039, 21.033226, 21.032613, 17.073128, 17.074895, 21.032988,
       21.032932, 21.034571, 17.084105, 14.371969, 21.033921, 17.075484,
       21.03321 , 23.814403, 17.090344, 17.070226, 23.813638, 23.817037,
       17.084025, 18.863684, 17.085811, 23.81275 , 23.809086, 23.811068,
       23.809736, 17.089055, 18.865229, 23.817073, 23.815204, 23.814758,
       23.816829, 23.811375, 23.816106, 17.065508, 17.067101, 17.090268,
       17.067453, 14.367503, 14.372463, 18.862915, 14.366689, 14.372818,
       14.367353, 14.372837, 18.874597, 18.87165 , 14.369286, 18.841071,
       18.835591, 22.411066, 22.425527, 22.412458, 22.420861, 22.411172,
       22.410445, 17.078596, 17.090891, 17.066719, 22.423861, 22.41916 ,
       22.424085, 18.835281, 22.415169, 17.090742, 17.091147, 18.949465,
       18.943306, 21.032869, 17.089464, 18.871602, 23.90499 , 23.90087 ,
       21.034175, 11.494157, 18.872535, 18.948171, 17.090716, 21.033586,
       18.948588, 18.948538, 23.906057, 11.082195, 11.103684, 11.082734,
       17.08942 , 17.086572, 17.086878, 21.034189, 21.033515, 21.033534,
       17.088827, 18.944356, 21.033187, 11.105334, 11.087046, 18.939943])

## **LIMPIEZA DE DATOS**
**Objetivo:** Tener un DF consistente

Indentifica las columnas con valores faltantes y aplica una estrategia de tratamiento adecuada

In [14]:
print("tipos de datos: ")
df.dtypes

tipos de datos:

Animal type             str
Country                 str
Weight kg           float64
Body Length cm      float64
Gender                  str
Animal code         float64
Latitude            float64
Longitude           float64
Animal name             str
Observation date        str
Data compiled by        str
dtype: object

In [15]:
print("\nValores faltantes: ")
display(
    df.isna()
        .sum()
        .sort_values(ascending=False)

)

Valores faltantes:

Animal code         1011
Animal name          959
Latitude              98
Longitude             98
Weight kg             27
Body Length cm        27
Animal type           20
Gender                19
Country               12
Observation date       0
Data compiled by       0
dtype: int64

Segun hallazgos del diagnostico inicial la columna de animal code no aporta informacion y debemos eliminarla. Tambien evidenciamos faltantes en Animal name, Latitude, logitude, weight kg, Body length cm, ANimal type y country

#### Eliminamos columna vacia

In [16]:
df = df.drop(columns="Animal code")

print(df.shape)
print("Animal code sigue presente?:", "Animal_code" in df.columns)

(1011, 10)
Animal code sigue presente?: False

Procedemos a hacer una evaluacion de las columnas con informacion tipo "Str" para ello se crea una lista con los nombres de las columnas y un ciclo para ir por cada una y contar los valores unicos en estas

In [17]:
columnas_categoricas = [
    "Animal name",
    "Animal type",
    "Gender",
    "Country",
    "Data compiled by"
    #Observation date 
    ]

for columna in columnas_categoricas:
    print(f"\n{'=' * 15} {columna} {'=' * 15}")
    print(df[columna].value_counts(dropna=False))

=============== Animal name ===============
Animal name
NaN           959
Bob Bobson     18
Basia          10
Lola            9
Lolek           4
Zuzia           4
Sissi           2
Puchatek        2
Szefu           1
Klucha          1
Bibi            1
Name: count, dtype: int64

=============== Animal type ===============
Animal type
red squirrel       543
hedgehog           274
lynx                61
European bison      49
red squirrell       22
NaN                 20
red squirel         14
lynx?               10
European bison™      6
European bisson      4
European buster      4
ledgehod             3
wedgehod             1
Name: count, dtype: int64

=============== Gender ===============
Gender
male              499
female            488
NaN                19
not determined      5
Name: count, dtype: int64

=============== Country ===============
Country
Poland            291
Germany           176
Slovakia          151
Hungary           146
Czech Republic    103
Austria            74
PL                 15
NaN                12
HU                 11
Hungry             10
CZ                  5
DE                  5
Czech               4
Australia           4
CC                  4
Name: count, dtype: int64

=============== Data compiled by ===============
Data compiled by
Anne Anthony     473
Bob Bobson       259
John Johnson     249
James Johnson     30
Name: count, dtype: int64

In [18]:
df[columnas_categoricas] = df[columnas_categoricas].fillna("unknown")
print(df[columnas_categoricas])

     Animal name      Animal type          Gender  Country Data compiled by
0        unknown          unknown         unknown  unknown    James Johnson
1        unknown          unknown         unknown  unknown    James Johnson
2          Szefu   European bison            male   Poland     Anne Anthony
3        unknown   European bison  not determined   Poland     Anne Anthony
4        unknown  European bison™          female   Poland     Anne Anthony
...          ...              ...             ...      ...              ...
1006        Lola     red squirrel          female   Poland     Anne Anthony
1007     unknown         hedgehog          female  Germany       Bob Bobson
1008     unknown         hedgehog          female  Germany       Bob Bobson
1009        Lola     red squirrel          female   Poland     Anne Anthony
1010     unknown         hedgehog          female  Hungary     Anne Anthony

[1011 rows x 5 columns]

In [19]:
df["Gender"].value_counts()

Gender
male              499
female            488
unknown            19
not determined      5
Name: count, dtype: int64

In [20]:
mapa_genero = {
    "male": "Male",
    "female": "Female",
    "unknown": "Unknown",
    "not determined": "Unknown"
}

df["Gender"] = df["Gender"].replace(mapa_genero)


print(df["Gender"].value_counts(dropna=False))
print("\nFaltantes en gender:", df["Gender"].isna().sum())

Gender
Male       499
Female     488
Unknown     24
Name: count, dtype: int64

Faltantes en gender: 0

Ahora pasamos a otro requisito: convertir tipos de datos. Observation date seguramente fue leída como texto (object), pero debe convertirse a fecha para poder analizarla correctamente.

In [21]:
print("Tipo actual:", df["Observation date"].dtype)

print("\nEjemplos de valores:")
print(df["Observation date"].head(10))

Tipo actual: str

Ejemplos de valores:
0    03.01.2024
1    03.02.2024
2    01.03.2024
3    01.03.2024
4    01.03.2024
5    01.03.2024
6    01.03.2024
7    01.03.2024
8    01.03.2024
9    01.03.2024
Name: Observation date, dtype: str

03.01.2024 usa el formato día.mes.año:  %d.%m.%Y

In [22]:
df["Observation date"] = pd.to_datetime(
    df["Observation date"],
    format="%d.%m.%Y",
    errors="coerce"
)

print("Nuevo tipo:", df["Observation date"].dtype)
print("\nFechas inválidas o faltantes:", df["Observation date"].isna().sum())
print("\nPrimeras fechas convertidas:")
print(df["Observation date"].head())

Nuevo tipo: datetime64[us]

Fechas inválidas o faltantes: 43

Primeras fechas convertidas:
0   2024-01-03
1   2024-02-03
2   2024-03-01
3   2024-03-01
4   2024-03-01
Name: Observation date, dtype: datetime64[us]

In [23]:
fechas_invalidas = df_raw.loc[
    df["Observation date"].isna(),
    "Observation date"
]

print("Cantidad de fechas inválidas:", fechas_invalidas.shape[0])
print("\nValores originales problemáticos:")
print(fechas_invalidas.value_counts(dropna=False))

Cantidad de fechas inválidas: 43

Valores originales problemáticos:
Observation date
5 May 2024    9
2 may 2024    7
6 May 2024    7
1 May 2024    6
7 May 2024    5
03.22.2024    2
3 May 2024    2
4 May 2024    2
03.13.2024    1
03.14.2024    1
8 May 2024    1
Name: count, dtype: int64

como hay formatos mezclados, debemos volver a construir la columna desde df_raw, no desde df, porque en df esos 43 valores ya fueron convertidos a NaT

In [24]:
df["Observation date"] = pd.to_datetime(
    df_raw["Observation date"],
    format="mixed",
    dayfirst=True,
    errors="coerce"
)

print("Tipo:", df["Observation date"].dtype)
print("Fechas faltantes o inválidas:", df["Observation date"].isna().sum())

Tipo: datetime64[us]
Fechas faltantes o inválidas: 0

La variable Observation date estaba almacenada como texto y presentaba formatos inconsistentes: día.mes.año, mes.día.año y fechas con meses escritos en inglés. Después de la transformación, la columna quedó sin valores faltantes.

### Estandarizacion de animal type

In [40]:
#Realizamos un diccionario con mapeo de variables
mapa_animal_type = {
    "red squireel": "Red squirrel",
    "red squirrel": "Red squirrel",
    "red squirel": "Red squirrel",

    "hedgehog": "Hedgehog",
    "ledgehod": "Hedgehog",
    "wedgehod": "Hedgehog",

    "lynx": "Lynx",
    "lynx?": "Lynx",

    "European bison": "European bison",
    "European bison™": "European bison",
    "European bisson": "European bison",
    "European buster": "European bison",

    "Unknown": "Unknown"
}

#Seleccionamos columna y actualizamos valores con .replace()
df["Animal type"] = df["Animal type"].replace(mapa_animal_type)

#Validamos ajustes
print(df["Animal type"].value_counts(dropna=False))
print("\nFaltantes en Animal type:", df["Animal type"].isna().sum())
print("\nNúmero de categorías:", df["Animal type"].nunique(dropna=False))

Animal type
Red squirrel      579
Hedgehog          278
Lynx               71
European bison     63
unknown            20
Name: count, dtype: int64

Faltantes en Animal type: 0

Número de categorías: 5

## NumPY
Utilizar NumPy para realizar transformaciones sobre el DataFrame.

In [41]:
#Crear una variable utilizando np.where()


np.where([[True, False], [True, True]],
         [[1, 2], [3, 4]],
         [[9, 8], [7, 6]])

array([[1, 8],
       [3, 4]])

Basado en el analizis inicial, tiene sentido estadisitico analizar un dato como "Weight kg" para entender sus valores superiores a 10kg o menos

In [42]:
weight = df["Weight kg"]
weight

df["weight category"] = np.where(
    weight > 10,
    "Above 10 kg",
    "10 kg or less"
)

df[["Weight kg", "weight category"]].head(20)

    Weight kg weight category
0         NaN   10 kg or less
1         NaN   10 kg or less
2     930.000     Above 10 kg
3     909.000     Above 10 kg
4     581.000     Above 10 kg
5     900.000     Above 10 kg
6     620.000     Above 10 kg
7      24.000     Above 10 kg
8      23.000     Above 10 kg
9       0.308   10 kg or less
10      0.348   10 kg or less
11      0.316   10 kg or less
12      0.340   10 kg or less
13      0.333   10 kg or less
14      0.265   10 kg or less
15        NaN   10 kg or less
16      0.261   10 kg or less
17      0.317   10 kg or less
18      0.328   10 kg or less
19      0.305   10 kg or less

In [43]:
mean = np.mean(weight)
print(f"El peso promedio de los animales en la base de datos es: ",  int(mean), "kg")

El peso promedio de los animales en la base de datos es:  39 kg

In [44]:
median = np.median(weight)
print(f" La mediana estadistica del peso es: ", median )

 La mediana estadistica del peso es:  nan

### **Análisis con groupby()**

 Cuál es el número de observaciones por tipo de animal?

In [49]:
cantidad_de_animales_por_tipo = df.groupby("Animal type").size() 
print(cantidad_de_animales_por_tipo)

Animal type
European bison     63
Hedgehog          278
Lynx               71
Red squirrel      579
unknown            20
dtype: int64

Cuál es el promedio de una variable numérica según el tipo de animal?

In [ ]:
promedio = cantidad_de_animales_por_tipo.mean()
print(promedio)

202.2

Cuál es el promedio de una variable numérica según el país?

In [62]:
AVG_Animal_type_segun_pais = df.groupby("Country")["Animal type"].count().mean()

print(AVG_Animal_type_segun_pais)

67.4


## Interpretacion de resultados
1. Polonia contribuye con la mayor cantidad de registros (291), lo que sugiere que la recolección en este país es más robusta o que las observaciones polacas son más frecuentes.  
2. La especie “red squirrel” domina el dataset con 543 registros (54 % de las observaciones). Esto indica que la fauna con mayor presencia o capacidad de observación está relacionada con especies pequeñas y muy comunes.  
3. El peso medio de los “European bison™” (688 kg) es significativamente superior al de otras especies, confirmando que son mamíferos de gran tamaño y que su presencia responde a criterios de viajeros más grandes y su búsqueda precisa.  
4. El rango de pesos de las ardillas (≈ 0.3–1 kg) muestra un poco de variabilidad, pero la desviación estándar es baja (≈ 0.05 kg), indicando que las muestras de “red squirrel” provienen de una población muy homogénea.